### PR TITLE
Report errors when LISTEN or UNLISTEN fail

### LINKED ISSUE #24: `listen` silently fails on a read replica
Read replicas fail on LISTEN:

```sql
postgres=# LISTEN pgrst;
ERROR:  cannot execute LISTEN during recovery

postgres=# select pg_is_in_recovery();
 pg_is_in_recovery 
-------------------
 t
(1 row)

# Also see https://stackoverflow.com/questions/70293290/can-you-perform-listen-unlisten-on-a-postgresql-read-replica
```

This currently fails silently on `hasql-notifications`, due to `listen` ignoring the error (`void`):

https://github.com/diogob/hasql-notifications/blob/c8f4956c2ee58ad619faa3a6c21bf968b1190b0c/src/Hasql/Notifications.hs#L120

Note: UNLISTEN doesn't fail on the replica, but it would still be good to not ignore the error there too.

### PR DESCRIPTION
**Pull request by diogob**
should take care of #24

### CODE REVIEW

**Comment by diogob** [comment]
@steve-chavez would you please review this code? If it fits your use case we should be ready for a release :smiley:

**Comment by steve-chavez** [comment]
@diogob Hm, just tested it and somehow it doesn't fail. My attempt on https://github.com/steve-chavez/postgrest/commit/65c00f4239d8c301640435d61916e6d09deb5173. Am I doing something wrong?

We use hasql-notifications like this https://github.com/PostgREST/postgrest/blob/d9a51f23ce7d407894cba546d8822d32d2ddca23/src/PostgREST/AppState.hs#L507-L508

Will keep digging..

---

The pg logs do show that an error did happen, still silent on PostgREST side though.
```
2024-05-03 15:18:06.042 UTC [1514621] LOG:  statement: LISTEN "pgrst"
2024-05-03 15:18:06.042 UTC [1514621] ERROR:  cannot execute LISTEN during recovery
2024-05-03 15:18:06.042 UTC [1514621] STATEMENT:  LISTEN "pgrst"
```

**Comment by diogob** [comment]
@steve-chavez I'll do some local testing with my test app and see what happens in the replica scenario

**Comment by diogob** [comment]
@steve-chavez I got it now, the code was not checking the result errors (which are different than the connection errors).
Now when testing locally on a read replica I get the error:

```sh
cabal exec hasql-notifications
hasql-notifications: ERROR:  cannot execute LISTEN during recovery
```

Could you test on your side once more before I merge?

**Comment by steve-chavez** [comment]
@diogob Works now! :raised_hands: 

```
05/May/2024:10:17:24 -0500: Could not listen for notifications on the pgrst channel. ERROR:  cannot execute LISTEN during recovery Retrying listening for notifications..
```

---

Before a new release, could you also allow [hasql-pool-1.2](https://hackage.haskell.org/package/hasql-pool-1.2)? :pray:

**Comment by diogob** [comment]
> Before a new release, could you also allow [hasql-pool-1.2](https://hackage.haskell.org/package/hasql-pool-1.2)? 🙏

@steve-chavez the new dependency was released in the [0.2.3.0](https://hackage.haskell.org/package/hasql-notifications-0.2.3.0)

**Pull request merged**
